MVCCore/Models/CreateTestVM.cs
using System.ComponentModel.DataAnnotations;

namespace MVCCore.Models
{
    public class CreateTestVM
    {
        [Display(Name="name"),Required(ErrorMessage ="requiredName")]
        public string Name { get; set; }
    }
}

MVCCore/Models/ErrorViewModel.cs
namespace MVCCore.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MVCCore/Controllers/HomeController.cs
using Microsoft.AspNetCore.Localization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Localization;
using MVCCore.BaseData;
using MVCCore.Models;
using System.Diagnostics;

namespace MVCCore.Controllers
{
    public class HomeController : BaseController
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IStringLocalizer<HomeController> _localizer;

        public HomeController(ILogger<HomeController> logger, IStringLocalizer<HomeController> localizer)
        {
            _logger = logger;
            _localizer = localizer;
        }

        public IActionResult Index()
        {
            ViewBag.WelcomeMSG = string.Format(_localizer["welcomeParam"], isArLang ? "عبدالرحمن" : "Abdalrhman");
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        public IActionResult TestLanguage()
        {
            return View();
        }
        public IActionResult TestLanguageViewModel()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }


        [HttpPost]
        public IActionResult SetLang(string culture, string returnUrl)
        {
            Response.Cookies.Append(
                CookieRequestCultureProvider.DefaultCookieName,
                CookieRequestCultureProvider.MakeCookieValue(new RequestCulture(culture)),
                new CookieOptions { Expires = DateTimeOffset.UtcNow.AddMonths(1) }
            );
            return LocalRedirect(returnUrl);
            //return Redirect(returnUrl);
        }
    }
}

MVCCore/Controllers/SourceController.cs
using AutoMapper;
using LogicHelper.Consts;
using Microsoft.AspNetCore.Mvc;
using MVCCore.BaseData;
using POS.BL.UOW;
using POS.DAL.Models;

namespace MVCCore.Controllers
{
    public class SourceController : BaseController
    {
        private readonly IUnitOfWork _uow;
        private readonly IMapper _mapper;
        public SourceController(IUnitOfWork uow,IMapper mapper)
        {
            _uow = uow;
            _mapper = mapper;
        }
        public async Task<IActionResult> Index(int sourceTypeId , int pageNo = 0)
        {
            int pageSize = 20;
            var data = await _uow.Sources.FindAllAsync(x => x.SourceTypeId == sourceTypeId,20,0,x => x.AName,OrderBy.Descending, new[] { "SourceType" });
            return View(data);   
        }


        public async Task<IActionResult> Form(int id)
        {
            var data = new SourceDTO();
            if (id > 0)
            {
                var test = await _uow.Sources.GetByIdAsync(id);
                data = _mapper.Map<SourceDTO>(test);
                data = data??new SourceDTO();
            }
            FormLoad(data);
            return View(data);   
        }
        async Task<SourceDTO> FormLoad(SourceDTO model)
        {
            model.SourceTypes = _mapper.Map<IEnumerable<SourceTypeDTO>>(await _uow.SourceType.GetAllAsync()).ToList();
            return model;
        }
    }
}

MVCCore/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">@ViewBag.WelcomeMSG</h1>
</div>

MVCCore/Views/Home/TestLanguage.cshtml
@using Microsoft.AspNetCore.Localization
@{
    ViewData["Title"] = localizer["testLanguage"];
}

@{
    var reqCul = Context.Features.Get<IRequestCultureFeature>();
}

<a class="btn btn-primary" asp-action="TestLanguageViewModel">@localizer["create"]</a>


<table class="table table-hover mt-4">
    <tr>
        <td>@localizer["culture"]</td>
        <td>@reqCul.RequestCulture.Culture.NativeName</td>
    </tr>
    <tr>
        <td>@localizer["date"]</td>
        <td>@DateTime.Now</td>
    </tr>
    <tr>
        <td>@localizer["currency"]</td>
        <td>@(9995.25.ToString("c"))</td>
    </tr>
    <tr>
        <td>@localizer["numbers"]</td>
        <td>@(18986.69m.ToString("F2"))</td>
    </tr>
</table>

MVCCore/Views/Home/TestLanguageViewModel.cshtml
@model MVCCore.Models.CreateTestVM


<form method="post">

    <div>
        <label asp-for="Name"></label>
        <input asp-for="Name" class="form-control" />
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>
    <button type="submit" class="btn btn-primary">@localizer["save"]</button>
</form>

@section Scripts{
    <partial name="_ValidationScriptsPartial" />
}

MVCCore/Views/Shared/_Layout.cshtml
@{
    var isRTL = CultureInfo.CurrentCulture.Name.StartsWith("ar");
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MVCCore</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MVCCore.styles.css" asp-append-version="true" />
    <link href="~/lib/font-awesome/css/all.min.css" rel="stylesheet" />
</head>
<body lang="en" dir="@(isRTL?"RTL":"LTR")">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MVCCore</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">@localizer["home"]</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="TestLanguage">@localizer["testLanguage"]</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Source" asp-action="index" asp-route-sourceTypeId=1>Customers</a>
                        </li>
                    </ul>
                </div>
                <div>
                    <partial name="_SetLanguage" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - MVCCore - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/lib/font-awesome/js/all.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

MVCCore/Views/Shared/_SetLanguage.cshtml
@using Microsoft.AspNetCore.Builder
@using Microsoft.AspNetCore.Http.Features
@using Microsoft.AspNetCore.Localization
@using Microsoft.AspNetCore.Mvc.Localization
@using Microsoft.Extensions.Options

@inject IViewLocalizer Localizer
@inject IOptions<RequestLocalizationOptions> LocOptions
@*
@{
    var requestCulture = Context.Features.Get<IHttpRequestFeature>();
    var cultureItems = locOption.Value.SupportedUICultures
    .Select(x => new SelectListItem { Value = x.Name, Text = x.DisplayName }).ToList();
}

<div title="@localizer["Request Culture provider:"] @requestCulture?.Provider?.GetType().Name">

</div>*@


@{
    var requestCulture = Context.Features.Get<IRequestCultureFeature>();
    var cultureItems = new List<SelectListItem>();
    //cultureItems.Add(new SelectListItem { Value = "", Text = Localizer["Select Lang"].Value });
    cultureItems.AddRange(LocOptions.Value.SupportedUICultures
        .Select(c => new SelectListItem { Value = c.Name, Text = c.NativeName })
        .ToList());
    var returnURL = string.IsNullOrEmpty(Context.Request.Path) ? "~/" : $"~{Context.Request.Path.Value}";
}

<div title="@Localizer["Request culture provider:"] @requestCulture?.Provider?.GetType().Name">
    <form id="selectLanguage" method="post" asp-controller="Home" asp-action="SetLang" asp-route-returnUrl="@returnURL" >
        @*<label asp-for="@requestCulture.RequestCulture.UICulture.Name">@Localizer["Language:"]</label>*@
        <select name="culture" onchange="this.form.submit();" asp-for="@requestCulture.RequestCulture.UICulture.Name" asp-items="cultureItems">
        </select>
    </form>
</div>

MVCCore/Views/Source/Form.cshtml
@model SourceDTO

@{
    ViewData["Title"] = "Form";
}

<h1>Form</h1>

<h4>Source</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Form">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="SourceTypeId" class="control-label"></label>
                <select class="form-contro" asp-for="SourceTypeId" asp-items="@(new SelectList(Model.SourceTypes,"Id","AName",Model.SourceTypeId))"></select>
                <input asp-for="SourceTypeId" class="form-control" />
                <span asp-validation-for="SourceTypeId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Code" class="control-label"></label>
                <input asp-for="Code" class="form-control" />
                <span asp-validation-for="Code" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AName" class="control-label"></label>
                <input asp-for="AName" class="form-control" />
                <span asp-validation-for="AName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EName" class="control-label"></label>
                <input asp-for="EName" class="form-control" />
                <span asp-validation-for="EName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address" class="control-label"></label>
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Tel" class="control-label"></label>
                <input asp-for="Tel" class="form-control" />
                <span asp-validation-for="Tel" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Phone" class="control-label"></label>
                <input asp-for="Phone" class="form-control" />
                <span asp-validation-for="Phone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Fax" class="control-label"></label>
                <input asp-for="Fax" class="form-control" />
                <span asp-validation-for="Fax" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="GovernorateId" class="control-label"></label>
                <input asp-for="GovernorateId" class="form-control" />
                <span asp-validation-for="GovernorateId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CityId" class="control-label"></label>
                <input asp-for="CityId" class="form-control" />
                <span asp-validation-for="CityId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    <script>        
        var custId =  parseInt($("#Id").val()) || 0;
        var masterControl =  "Source";


    </script>
}

MVCCore/Views/Source/Index.cshtml
@model IEnumerable<Source>
@using Microsoft.AspNetCore.Builder
@using Microsoft.AspNetCore.Localization
@using Microsoft.Extensions.Options

@inject IOptions<RequestLocalizationOptions> LockOptions

@{
    var requestCul = Context.Features.Get<IRequestCultureFeature>();
}
<h1></h1>
<h2> @requestCul.RequestCulture.Culture.Name </h2>
@if (!Model.Any())
{

    <div class="alert alert-warning" role="alert">
        لا يوجد بيانات
    </div>
}
else
{
    <table class="table table-striped">
        <thead>
            <tr class="" style="color:red;">
                <th  scope="col">الكود</th>
                <th  scope="col">النوع</th>
                <th  scope="col">الإسم العربي</th>
                <th  scope="col">الإسم الإنجليزي</th>
                <th  scope="col">العنوان</th>
                <th  scope="col">رقم الهاتف</th>
                <th scope="col"> <i class="fa fa-cog"></i> </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <th scope="row">@item.Code</th>
                    <td>@item.SourceType.AName</td>
                    <td>@item.AName</td>
                    <td>@item.EName</td>
                    <td>@item.Address</td>
                    <td>@item.Tel</td>
                    <td>

                        <a class="btn btn-outline-warning" asp-area="" asp-controller="Source" asp-action="Details" asp-route-id="@item.Id" style="color:black;">  <i class="fa fa-eye"></i> </a>
                        <a class="btn btn-outline-primary" asp-area="" asp-controller="Source" asp-action="Form" asp-route-id="@item.Id">  <i class="fa fa-edit"></i> </a>
                        <a class="btn btn-outline-danger" asp-area="" asp-controller="Source" asp-action="Delete" asp-route-id="@item.Id">  <i class="fa fa-trash"></i> </a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
}